---
- name: Deploy TP Foyer
  hosts: docker_hosts
  tasks:
    - name: Remove old containers
      shell: |
        docker rm -f objective_gagarin zen_shockley wizardly_lamport confident_leakey ecstatic_cray k3s-server || true
        
    - name: Ensure TP Foyer is running
      shell: |
        # Check if containers exist and recreate if needed
        if ! docker ps -q -f name=mysqldb; then
          docker run -d \
            --name mysqldb \
            --network spring-mysql \
            -e MYSQL_ALLOW_EMPTY_PASSWORD=yes \
            -e MYSQL_DATABASE=tp-foyer \
            -p 3306:3306 \
            mysql:5.7
        fi
        
        if ! docker ps -q -f name=app-tp-foyer; then
          docker run -d \
            --name app-tp-foyer \
            --network spring-mysql \
            -p 8089:8089 \
            medhadji/tp-foyer:5.0.0
        fi

    - name: Show running containers
      shell: docker ps
      register: container_status

    - name: Display status
      debug:
        var: container_status.stdout_lines
