---
- name: Deploy application
  hosts: localhost
  become: true

  vars:
    container_name: tp-foyer-ansible  # Changed container name
    docker_image: omarabidi/tp-foyer:5.0.0
    mysql_host: mysqldb
    mysql_port: 3306
    mysql_database: tpfoyer
    mysql_user: root
    mysql_password: ""
    network_name: reformed2d_devops_default

  tasks:
    - name: Pull Docker image
      community.docker.docker_image:
        name: "{{ docker_image }}"
        source: pull
        force_source: true

    - name: Create and start container
      community.docker.docker_container:
        name: "{{ container_name }}"  # Will create tp-foyer-ansible
        image: "{{ docker_image }}"
        state: started
        restart_policy: always
        ports:
          - "8090:8089"  # Changed port to avoid conflict
        networks:
          - name: "{{ network_name }}"
        env:
          SPRING_DATASOURCE_URL: "jdbc:mysql://{{ mysql_host }}:{{ mysql_port }}/{{ mysql_database }}?createDatabaseIfNotExist=true"
          SPRING_DATASOURCE_USERNAME: "{{ mysql_user }}"
          SPRING_DATASOURCE_PASSWORD: ""

    - name: Check container status
      community.docker.docker_container_info:
        name: "{{ container_name }}"
      register: result

    - name: Display container status
      debug:
        var: result.container.State