---
- name: Deploy application
  hosts: localhost
  become: true

  vars:
    container_name: app-tp-foyer
    docker_image: omarabidi/tp-foyer:5.0.0
    mysql_host: mysqldb
    mysql_port: 3306
    mysql_database: tpfoyer
    mysql_user: root
    mysql_password: ""

  tasks:
    # Add this new task to create network
    - name: Create Docker network
      community.docker.docker_network:
        name: app-network
        state: present

    - name: Pull Docker image
      community.docker.docker_image:
        name: "{{ docker_image }}"
        source: pull
        force_source: true

    - name: Remove existing container
      community.docker.docker_container:
        name: "{{ container_name }}"
        state: absent
        force_kill: yes
      ignore_errors: yes

    - name: Create and start container
      community.docker.docker_container:
        name: "{{ container_name }}"
        image: "{{ docker_image }}"
        state: started
        restart_policy: always
        ports:
          - "8089:8089"
        networks:
          - name: app-network
        env:
          SPRING_DATASOURCE_URL: "jdbc:mysql://{{ mysql_host }}:{{ mysql_port }}/{{ mysql_database }}?createDatabaseIfNotExist=true"
          SPRING_DATASOURCE_USERNAME: "{{ mysql_user }}"
          SPRING_DATASOURCE_PASSWORD: ""

    - name: Check container status
      community.docker.docker_container_info:
        name: "{{ container_name }}"
      register: result

    - name: Display container status
      debug:
        var: result.container.State